### ISSUE TITLE
Use seven rules of good commit messages?

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/cz-freecodecamp#2]
If we plan on using this as a standard way of making commit messages on the main repo, maybe we should consider using these guidelines ["The seven rules of a great Git commit message"](https://chris.beams.io/posts/git-commit/#seven-rules).

Here they are:

- [x] **Separate subject from body with a blank line** (Already implemented)
- [x] **Limit the subject line to 50 characters** (https://github.com/freeCodeCamp/cz-freecodecamp/issues/6)
- [x] **Capitalize the subject line** (https://github.com/freeCodeCamp/cz-freecodecamp/issues/7) 
- [x] **Do not end the subject line with a period** (https://github.com/freeCodeCamp/cz-freecodecamp/pull/11)
- Use the imperative mood in the subject line (This can be shown and suggested with examples) (Related https://github.com/freeCodeCamp/cz-freecodecamp/pull/10)
- [x] **Wrap the body at 72 characters** (https://github.com/freeCodeCamp/cz-freecodecamp/issues/6)
- [x] Use the body to explain what and why vs. how (This can be suggested in the question) (https://github.com/freeCodeCamp/cz-freecodecamp/pull/12)

The bold items are things I think are easily enforceable based on the commitzen framework. Number 5 might be something we can highly suggest using examples. And number 7 can be optional, but I guess you could break up the commit message as "What changes did you make" + "Why and how did you make this change".

**Comment by BerkeleyTrue** [comment]
Sure! 👍

**Comment by erictleung** [comment]
Closing as all rules have been applied to the adapter with the referenced PRs.
